import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useLocation } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { LogOut, Shield, Layout, User, HelpCircle } from "lucide-react";
export const Header = () => {
    const { user, logout } = useAuth();
    const location = useLocation();
    const isActive = (path) => location.pathname === path;
    return (_jsxs("header", { className: "app-header", children: [_jsxs(Link, { to: "/", className: "logo", children: ["OIDC Provider ", _jsx("span", { className: "logo-dot" })] }), _jsxs("nav", { className: "app-nav", style: { alignItems: "center" }, children: [_jsx(Link, { to: "/o/authenticate", className: isActive("/o/authenticate") ? "active" : "", children: _jsxs("span", { style: { display: "inline-flex", alignItems: "center", gap: "6px" }, children: [_jsx(User, { size: 15 }), " Auth"] }) }), _jsx(Link, { to: "/clients/register", className: isActive("/clients/register") ? "active" : "", children: _jsxs("span", { style: { display: "inline-flex", alignItems: "center", gap: "6px" }, children: [_jsx(Layout, { size: 15 }), " Dev Client"] }) }), user?.isAdmin && (_jsx(Link, { to: "/admin/dashboard", className: isActive("/admin/dashboard") ? "active" : "", children: _jsxs("span", { style: { display: "inline-flex", alignItems: "center", gap: "6px" }, children: [_jsx(Shield, { size: 15 }), " Admin"] }) })), _jsx("a", { href: "/.well-known/openid-configuration", target: "_blank", rel: "noreferrer", children: _jsxs("span", { style: { display: "inline-flex", alignItems: "center", gap: "6px" }, children: [_jsx(HelpCircle, { size: 15 }), " Discovery"] }) }), user && (_jsxs("div", { style: { display: "flex", alignItems: "center", gap: "12px", marginLeft: "12px", borderLeft: "1px solid var(--border)", paddingLeft: "16px" }, children: [_jsx("span", { style: { fontSize: "0.85rem", color: "#ffffff", fontWeight: 500 }, children: user.name }), _jsxs("button", { onClick: logout, className: "btn btn-secondary", style: { height: "2rem", padding: "0 10px", fontSize: "0.8rem", gap: "4px" }, title: "Logout", children: [_jsx(LogOut, { size: 12 }), "Logout"] })] }))] })] }));
};
//# sourceMappingURL=Header.js.map